### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by jzerick** [periscope-ps/unis#14]
In models.py, line 474:

print "Error loading cached schema for %s: %s" % (s, e) 
gives a syntax error. Adding parentheses, like so,
print("Error loading cached schema for %s: %s" % (s, e)) 
is accepted by the interpreter.

**Comment by gskip17** [comment]
Python 3 - print("Foo")
Python 2 - print "Foo"

Is this what you mean?

**Comment by jzerick** [comment]
Pretty sure it's an issue on my end.
